### ISSUE TITLE
sift({ $lt: new Date() })(null) is no longer false

### ISSUE THREAD

**Issue by marwej** [crcn/sift.js#176]
My app depends on these three test cases. The third one seems to fail since version 11. Was that a planned change? (If so, I need to adapt my app to this new situation.)

```javascript
expect(sift({ $lt: new Date() })(new Date('2010-01-01'))).toBe(true);
expect(sift({ $lt: new Date() })(new Date('2030-01-01'))).toBe(false);
expect(sift({ $lt: new Date() })(null)).toBe(false);
```

**Comment by crcn** [comment]
Fix should be up now on NPM as `11.1.0`. 

Definitely not a planned change, thanks for the catch. I added some tests too so that this doesn't happen again. 

The _main_ issue is that in JavaScript, `null < new Date()` is `true`, whereas in `MongoDB` it's `false`. Looks like MongoDB checks the data type since `null > new Date()` is _also_ `false`. `"4" < 5` is also `false`, as well as `"5" > 4`. I added those particular cases in.
