### ISSUE TITLE
nested $in rule doesn't work

### ISSUE THREAD

**Issue by simoami** [crcn/sift.js#193]
First of all, thanks for such a great project!

Given the following project resource:
```
const project = {
  memberships: [
      {id: 1, roleId: 1, membershipId: 1, role: { slug: 'project_owner'}},
      {id: 2, roleId: 2, membershipId: 2, role: { slug: 'collaborator'}},
      {id: 3, roleId: 3, membershipId: 3, role: { slug: 'observer'}},
  ]
}
```
A project **collaborator** (membershipId: 2) or **observer** (membershipId: 3) should be able to read the project above per the following rule:
```
canRead = membershipId => sift({ 
  memberships: {
    $elemMatch: { role: { slug: { $in: ['collaborator', 'observer'] } }, membershipId }
  }
})
```
So, these assertions should pass:
```
assert(canRead(2)(project) === true, 'collaborator should read project')
assert(canRead(3)(project) === true, 'observer should read project')
```
Unfortunately, they don't. 

If on the other hand, I change the rule to the following to replace the behavior of `$in` with `$or`, then the assertions work:
```
canRead = membershipId => sift({
  memberships: {
    $elemMatch: {
      $or: [
        { role: { slug: 'collaborator' }, membershipId },
        { role: { slug: 'observer' }, membershipId }
      ]
    }
  }
})
```

Is this expected?

**Edit:**
if I specify the path `role.slug` as a string then `$in` works:
```
canRead = membershipId => sift({
  memberships: {
      $elemMatch: {
        'role.slug': { $in: ['collaborator', 'observer'] },
        membershipId
      }
  }
})
```

**Comment by crcn** [comment]
> Is this expected?

Yep! This is all expected behavior based on MongoDB, but I agree that it's not that intuitive 😅. Your solution is spot on. 

As to _why_ your original code didn't work - operators (`$in`, `$or`, etc) can't be nested unless `$elemMatch` is used. So this doesn't work:

```javascript
sift({ role: { slug: { $in: ['collaborator'] }}});
```

☝This is a _strict_ equality since `slug` is not an operator, so everything within `slug` is treated like a vanilla object. You can observe this behavior even in MongoDB by trying this:

```
db.something.insert({ role: { slug: { $in: ['collaborator'] }}})
```

Then to query it:

```
db.something.find({ role: { slug: { $in: ['collaborator'] }}})
```
