### ISSUE TITLE
How to get the path matching with the dot path syntax ?

### ISSUE THREAD

**Issue by J3m5** [crcn/sift.js#205]
Hi, I would like to know if it would be possible, when working with arrays, to get the path that matched with the condition.

```js
const data = { a: [{ b: 1 }, { b: 2 }] };

const result = sift({ "a.b": 1 }, data);
// --> a[0].b

```

Would it be feasible with a custom operator or is there a place where I can grab that info ?

Thank you

**Comment by crcn** [comment]
oooh interesting idea. Right now the library doesn't support that, but I _think_ it can be done. If you want, you're welcome to submit a PR with that has this behavior, and I'll merge it in. 👍🏻

**Comment by J3m5** [comment]
I've looked at the source code and it seems that we would need to store the path at each [`walkKeyPathValues`](https://github.com/crcn/sift.js/blob/ec85ccaaa0c85f30e009ff7435512942e114af7e/src/core.ts#L79) call.

I'm wondering if this behavior should be only enabled with an option, like the [$explain](https://docs.mongodb.com/manual/reference/operator/meta/explain/#metaOp._S_explain) operator.

And for the returned information, we might want to return an object in case there are multiple paths like:
```js
const data = { a: [{ b: 1, c: 3 }, { b: 2, c: 4 }] };

const result = sift({ "a.b": 1, "a.c": 4, $explain: 1 }, data);

--> { "a.b": "a[0].b", "a.c": "a[1].c" }
```
What do you think ?

**Comment by crcn** [comment]
Ahh, I got it. That's pretty specific functionality that I'm not sure Sift can support very easily -- everything's built around filtering data. 

You should take a look at [UCast]((https://github.com/stalniy/ucast). It's a new MongoDB query library, but looks really promising. I think it may be able to do what you want - @stalniy would have better thoughts around this.

**Comment by stalniy** [comment]
Hi @J3m5 

In terms of ucast, you need:
- `MongoQueryParser` - implemented in `@ucast/mongo`
- operators from `JsInterpreter` - implemented in `@ucast/js`
- custom js interpreter with logic to aggregate matching path instead of aggregating resulting value.

If you want to learn more, start from [here](https://github.com/stalniy/ucast/blob/master/packages/core/README.md)

This is not something I plan to add ucast at least for now, because its main goal is to translate conditions from language to another (e.g., mongo query -> SQL, query string -> Mongo query, etc)

**Details:**  theoretically it's possible to do. Currently, `@ucast/mongo` provides a `MongoQueryParser` class, which you can use to parse any mongo query into AST (a tree of objects, you can think of it as something similar to XML tree). Having these objects, you can iterate over them to "interpret" them in anyway you need (e.g., XML can be interpreted as RSS, data transfer object or HTML).  

So, during iteration you can use operator interpreters from `@ucast/js` (e.g., `$lt`, `$gt`, $in`, `$eq`, etc) to get boolean result, also you need to aggregate path down the tree. As soon as operator returns true for your desired case, just stop iteration and return aggregated path.

**Comment by crcn** [comment]
Closing this for now since @stalniy seems to have a good fix.
