### ISSUE TITLE
Any interest or plan to port sift to CSharp?

### ISSUE THREAD

**Issue by thardy** [crcn/sift.js#249]
I have an interest in having a CSharp (C#) version of this library.  If any of the existing contributors have a similar interest or would simply be interested in helping out, please let me know.

Alternatively, if you know of an existing module or way to execute MongoDb shell queries against in-memory app-state in C#, please let me know.

**Comment by crcn** [comment]
I think at this point I don't plan on doing anything big with Sift since I'm mostly focused on other things. Though, If you start a CSharp project, I'd be happy to help spitball around some ideas. 👍

**Comment by jefflord** [comment]
I am interested in this also. I have started using sift.js in a number of places and ways and it's amazing. I have also created methods to convert the filter syntax to SQL/Text for other uses and create a nice GUI for building complex mongo filters. 

I now would like to use it on the back end but it's way too slow to use in Jint (https://github.com/sebastienros/jint), though it does work. Data marshalling is slow and also the filtering is slow. I assume this is due to Jint and not "sift.js". 

Being able to build filters that can be applied on the front or back end would be great. @crcn, if I start this project, still think you can share some wisdom?

**Comment by jefflord** [comment]
OK, that's great. I don't know when I will try to start on this since I have a couple things in the way, but I will certainly make it clear here.

I will go ahead and mention that I don't think that F# is more performant than C#, since they are both .Net languages. There are cases/projects that it might make code _writing_ faster, but that's only if you have that situation AND you are proficient with F#.   

I am not proficient with F# (I don't "know" it at all. I do know C# and VB.net pretty well. 

Also, for my needs I need to target .Net Standard 2.0, because I need this to run in .net framwork 4.8. I think this means access to C# <= 8.0. 

I hope this does not change your mind.

**Comment by thardy** [comment]
Any .net solution would have value.  Once something is up and running, it probably wouldn't be difficult to make a version in C# 10 from it.

**Comment by jefflord** [comment]
True. Which language feature of C# 10 do you think would benefit this? I don't know yet, but I am guessing that some reflection might be needed I think .net 7 and 8 have improvements there.

**Comment by thardy** [comment]
Mainly Records, but the principles of functional programming, like Pure Functions and Partial Function Application seem like they would be great for any query language.  I watched the following course on Pluralsight about a year ago when I was thinking about tackling this port - https://www.pluralsight.com/courses/c-sharp-10-functional.  I haven't done any functional programming though, so I didn't have enough experience to continue with very limited time.

**Comment by jefflord** [comment]
I don't know how right know to make use of that since nothing has been started. But I will say from a quick look "Partial Function Application" looks really neat. I would like to play with that to see how it would work with nest closures.

I hope I can start on this in the next month.
